# Generated by Django 4.1.1 on 2022-09-10 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(default='tax_rate', max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('country', models.CharField(max_length=2)),
                ('created', models.IntegerField(default=1662830789)),
                ('description', models.CharField(default='VAT Germany', max_length=255)),
                ('display_name', models.CharField(default='VAT', max_length=255)),
                ('inclusive', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(max_length=255)),
                ('livemode', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=19.0)),
                ('state', models.CharField(max_length=25, null=True)),
                ('tax_type', models.CharField(default='vat', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.item')),
                ('tax', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.tax')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.item')),
                ('tax', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.tax')),
            ],
        ),
    ]
