# Generated by Django 4.1.1 on 2022-09-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_discount_tax_taxrate_dynamictaxrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictaxrate',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tax'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created',
            field=models.IntegerField(default=1662832248),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tax'),
        ),
    ]
