# Generated by Django 4.1.1 on 2022-09-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_dynamictaxrate_tax_alter_tax_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamictaxrate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tax_rates_set', to='app1.item'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='created',
            field=models.IntegerField(default=1662832559),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates_set', to='app1.item'),
        ),
    ]
