# Generated by Django 4.1.1 on 2022-09-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_dynamictaxrate_item_alter_tax_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='item',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='tax',
        ),
        migrations.DeleteModel(
            name='DynamicTaxRate',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='TaxRate',
        ),
    ]
