# Generated by Django 4.1.1 on 2022-09-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_discount_item_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_id', models.CharField(default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tax_rates', to='app1.item')),
            ],
        ),
        migrations.CreateModel(
            name='FixedTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_id', models.CharField(default='', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_tax_rates', to='app1.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
