# Generated by Django 4.1.1 on 2022-09-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_dynamictax_fixedtax_delete_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_id', models.CharField(default=None, max_length=255, null=True)),
                ('object', models.CharField(default='tax_rate', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('country', models.CharField(default='US', max_length=2)),
                ('created', models.IntegerField(default=None, null=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('display_name', models.CharField(default='VAT', max_length=255)),
                ('inclusive', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(default='US - CA', max_length=255)),
                ('livemode', models.BooleanField(default=False)),
                ('percentage', models.FloatField(default=7.25)),
                ('state', models.CharField(default=None, max_length=255, null=True)),
                ('tax_type', models.CharField(default='vat', max_length=255)),
            ],
        ),
    ]
