# Generated by Django 4.1.1 on 2022-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_taxrate_created_alter_taxrate_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='description',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='tax_rate_id',
            field=models.CharField(default='Unknown', max_length=255, null=True),
        ),
    ]
