# Generated by Django 4.1.1 on 2022-09-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_taxrate_description_alter_taxrate_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictax',
            name='tax_rate_id',
        ),
        migrations.RemoveField(
            model_name='fixedtax',
            name='tax_rate_id',
        ),
        migrations.AddField(
            model_name='dynamictax',
            name='tax_rate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tax_rates', to='app1.taxrate'),
        ),
        migrations.AddField(
            model_name='fixedtax',
            name='tax_rate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_tax_rates', to='app1.taxrate'),
        ),
    ]
