# Generated by Django 4.1.1 on 2022-09-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_dynamictax_tax_rate_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('object', models.CharField(default='coupon', max_length=255)),
                ('duration_in_months', models.PositiveIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('object', models.CharField(default='promotion_code', max_length=255)),
                ('coupon', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.coupon')),
            ],
        ),
        migrations.AddField(
            model_name='discount',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='app1.coupon'),
        ),
        migrations.AddField(
            model_name='discount',
            name='promotion_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='app1.promocode'),
        ),
    ]
