# Generated by Django 4.1.1 on 2022-09-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_coupon_promocode_discount_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='percent_off',
            field=models.FloatField(default=0.0),
        ),
    ]
