# Generated by Django 4.1.1 on 2022-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_coupon_percent_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='duration',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
