# Generated by Django 4.1.1 on 2022-09-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_coupon_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='app1.order'),
        ),
    ]
